"""add profile completion tracking

Revision ID: 3dd51f46be18
Revises: b19f72a13604
Create Date: 2025-08-15 12:16:23.229897

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dd51f46be18"
down_revision: Union[str, Sequence[str], None] = "b19f72a13604"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("profile_completed", sa.Boolean(), nullable=False))
    op.add_column(
        "users", sa.Column("profile_completed_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_completed_at")
    op.drop_column("users", "profile_completed")
    # ### end Alembic commands ###
