"""split name into first_name last_name and add age as integer

Revision ID: bb6b2306c35a
Revises: 3dd51f46be18
Create Date: 2025-08-24 15:24:20.353562

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb6b2306c35a"
down_revision: Union[str, Sequence[str], None] = "3dd51f46be18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server defaults to handle existing rows
    op.add_column(
        "users", sa.Column("first_name", sa.String(), nullable=False, server_default="")
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(), nullable=False, server_default="")
    )
    op.add_column("users", sa.Column("age", sa.Integer(), nullable=True))
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "name",
            sa.VARCHAR(),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "age")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
